### ISSUE TITLE
NaNs from the usage API not returning totals for the last day

### ISSUE THREAD

**Issue by raynervintervoll** [github-copilot-resources/copilot-metrics-viewer#16]
Cumulatives / totals are giving not-a-number on our metric data. It seems to be due to the Usage API not returning totals for the last day in the extract. Not sure why not, I guess that might be a community question. Example:

```
{
        "day": "2024-04-23",
        "breakdown": [
            {
                "language": "java",
                "editor": "jetbrains",
                "suggestions_count": 56,
                "acceptances_count": 16,
                "lines_suggested": 99,
                "lines_accepted": 20,
                "active_users": 2
            },
            {
                "language": "kotlin",
                "editor": "jetbrains",
                "suggestions_count": 27,
                "acceptances_count": 8,
                "lines_suggested": 41,
                "lines_accepted": 7,
                "active_users": 2
            },
```

**Comment by martedesco** [comment]
Thanks for reporting it @raynervintervoll ! I am following this one up with the Engineering team.

**Comment by raynervintervoll** [comment]
Thanks a lot for following up. Perhaps worth mentioning that our org is also returning 0 for all days and fields related to Chat, which I am pretty sure isn't correct either.

**Comment by martedesco** [comment]
@raynervintervoll , the team has acknowledged the issue and has already fixed it. 🎉 

> Perhaps worth mentioning that our org is also returning 0 for all days and fields related to Chat, which I am pretty sure isn't correct either.

We only backfilled Chat data for the 23rd April, so historical Chat data won't be available. 

I will close this issue meanwhile, feel free to re-open it if issue persists. 🙏🏼

**Comment by raynervintervoll** [comment]
@martedesco Thanks for your help, Marcio. The issue still persists due to the 23rd of April still missing the totals, the 24th is however fine.  I am not able to re-open since I am not a collaborator. 

` {
        "day": "2024-04-23",
        "breakdown": [
            {`

**Comment by martedesco** [comment]
@raynervintervoll , in this case it is better to [create a support ticket](https://docs.github.com/en/enterprise-cloud@latest/support/contacting-github-support/creating-a-support-ticket#creating-a-support-ticket) as my colleagues from support will be able to check on this data for your organization.
