### ISSUE TITLE
Push up support path in the README

### ISSUE THREAD

**Issue by djopatrny** [github-copilot-resources/copilot-metrics-viewer#26]
Recommend emphasizing that support / questions should be submitted as an issue on this repo, not through GitHub support, either by pushing it up in the Readme or in some other way making it more prominent

**Comment by martedesco** [comment]
Thanks @djopatrny ! [Fixed in this commit](https://github.com/github-copilot-resources/copilot-metrics-viewer/commit/a00778d55dc8145edbf446bb09b90e9c935184db).
