### ISSUE TITLE
Percentage calculations seem to be off

### ISSUE THREAD

**Issue by jasontempleman-eaton** [github-copilot-resources/copilot-metrics-viewer#31]
Can someone please explain how the average calculations are computed?

Looking at the values in the readme for Cumulative Number of Accepted Prompts (50734) and Cumulative Number of Suggested Prompts (199097) I would expect the average would be 50734 / 199097 * 100 or 25.48% whereas the image shows 22.19%

I ran this locally again my Enterprise and the values are 20024 and 68238 so I would expect an average of 29.34% yet the value given is 20.54%

I would like to understand where these differences are coming from so that I can make sure I have the correct values.

**Comment by mbroton** [comment]
From what I see in `src/components/MetricsViewer.vue` there is calculation of `acceptanceRateAverage` done based on daily average value, instead of basing it on the total numbers. I would assume that's the issue, but I didn't dive too deep into the code, so I might be wrong.

**Comment by martedesco** [comment]
@mbroton - that's correct! I believe we should favour total number of suggestions / number of accepted prompts. I'm bringing up a fix for it.

**Comment by martedesco** [comment]
Fixed in [this PR](https://github.com/github-copilot-resources/copilot-metrics-viewer/pull/34). It will be available in the release v1.5 coming tomorrow. Thanks @jasontempleman-eaton for raising this.
