### ISSUE TITLE
Update access rights for github token?

### ISSUE THREAD

**Issue by msfe** [github-copilot-resources/copilot-metrics-viewer#33]
In the readme the following information is provided.

> VUE_APP_GITHUB_TOKEN
> Specifies the GitHub Personal Access Token utilized for API requests. Generate this token with the following scopes: copilot, manage_billing:copilot, manage_billing:enterprise, read:enterprise, admin:org.

I believe that `admin:org` is overkill. When I did my local setup, I used the less intrusive scope `read:org`, and it worked just fine. If there is no functionality I'm missing, I would suggest that the README be updated to adhere to the principle of least privilege.

**Comment by martedesco** [comment]
@msfe , it could be. The README follows the guidelines of the [API documentation](https://docs.github.com/en/rest/copilot/copilot-usage?apiVersion=2022-11-28#get-a-summary-of-copilot-usage-for-organization-members) which mentions `admin:org` . 

@djopatrny , do you have any comments about this? 🙇

**Comment by djopatrny** [comment]
I believe a recent update may have added the `read:org` scope. The documentation update should go in soon.

**Comment by martedesco** [comment]
As the docs have been updated and admin permissions requirement has been removed, I updated [on this PR](https://github.com/github-copilot-resources/copilot-metrics-viewer/pull/61) the references to admin:enterprise and admin:org. Thanks for raising this.
