### ISSUE TITLE
README Seat Analysis image update 

### ISSUE THREAD

**Issue by martedesco** [github-copilot-resources/copilot-metrics-viewer#35]
We might need to update this image once the changes have been implemented 🙏🏼

_Originally posted by @martedesco in https://github.com/github-copilot-resources/copilot-metrics-viewer/pull/32#discussion_r1620383407_

**Comment by DevOps-zhuang** [comment]
> ```
>           We might need to update this image once the changes have been implemented 🙏🏼
> ```
> 
> _Originally posted by @martedesco in [#32 (comment)](https://github.com/github-copilot-resources/copilot-metrics-viewer/pull/32#discussion_r1620383407)_

in the main branch, it seems the url links is as below. and it is not the old link to my fork repo, so do we still need to change it? thanks) @martedesco 

https://private-user-images.githubusercontent.com/54096296/334353713-d1fa9d1d-4fab-4e87-84ba-7be189dd4dd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MTAwMzIsIm5iZiI6MTcxNzQwOTczMiwicGF0aCI6Ii81NDA5NjI5Ni8zMzQzNTM3MTMtZDFmYTlkMWQtNGZhYi00ZTg3LTg0YmEtN2JlMTg5ZGQ0ZGQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDEwMTUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1NWExMTJjMTUwZjNiM2VmYTY4OTJlMmUxNWUyYjhlNTNiNDk1ZjlmNjA2ZWNkMzE5YmNlZjkwMGYzYjFkNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MOd9InAVCbXpZH70-Kvz_OMwoNHIn7S1w0lfNRDIxWg

**Comment by martedesco** [comment]
Image has been updated in a later commit 👍🏼
