### ISSUE TITLE
Is Seat count available in Enterprise metrics

### ISSUE THREAD

**Issue by romeroej-inch** [github-copilot-resources/copilot-metrics-viewer#41]
Is Seat count available in Enterprise metrics?

**Comment by DevOps-zhuang** [comment]
Currently, No. becasue the current Seat API only support organization level. Once the API  support Enterprise , we will add support in copilot view soon :-)

**Comment by romeroej2** [comment]
Hi, yes i checked that. What i did was that even if you are in enterprise you can see your "organizations" perhaps there is an api that gives you the Orgs in an Ent, and then you can use a select the org detail you want to see. (it actually works well if you want to se per org data)

**Comment by martedesco** [comment]
> The **Enterprise** [GitHub Copilot seats api](https://docs.github.com/en/rest/copilot/copilot-user-management?apiVersion=2022-11-28#list-all-copilot-seat-assignments-for-an-enterprise) has been published today.

Yes, the update is coming soon!

**Comment by martedesco** [comment]
Included in [release version 1.6](https://github.com/github-copilot-resources/copilot-metrics-viewer/releases/tag/v1.6)! Thanks @DevOps-zhuang for the great work 🚀
