### ISSUE TITLE
Data Refresh Rate

### ISSUE THREAD

**Issue by vaishnav-canarys** [github-copilot-resources/copilot-metrics-viewer#44]
Once this is deployed and set up as a dashboard, does the tool automatically sync the data every day.

**Comment by DevOps-zhuang** [comment]
Currently, it doesn't support auto sync, and it is in backlog to add such features.  consider to save the fetched data to file or SQL.

**Comment by vaishnav-canarys** [comment]
So @DevOps-zhuang to reflect any new data, should we stop and start the app again

**Comment by martedesco** [comment]
> So [@DevOps-zhuang](https://github.com/DevOps-zhuang) to reflect any new data, should we stop and start the app again

API is called when the application is loaded in the browser at this moment the Organization or Enterprise tab should be selected and displayed. When the user refreshes the page in the browser, the API is called again. The API call happen once per refresh and the same API response is used to feed the charts in all the tabs! Hope it helps 👍🏼
