### ISSUE TITLE
Filtering on projects, developers, teams

### ISSUE THREAD

**Issue by 64dude** [github-copilot-resources/copilot-metrics-viewer#47]
It would be useful to filter metric results on users, projects, teams. I don't see a current way of doing this. Thoughts? 
Thanks #

**Comment by DevOps-zhuang** [comment]
Currently, for usage API, there is no such informaiton within it. and teams support for usage is planned, will consider it once the teams support is ready from API side.

**Comment by martedesco** [comment]
@64dude, the team slicing API is planned to come back by end of July.

**Comment by DevOps-zhuang** [comment]
[like]  Junqian Zhuang reacted to your message:
________________________________
