### ISSUE TITLE
Are the enterprise members copilot access including the organization members metrics ?

### ISSUE THREAD

**Issue by vineethj1729** [github-copilot-resources/copilot-metrics-viewer#70]
**To describing my question**: 

Earlier i do have an organization permission. After the tokens are expired for that permission, we created the tokens for enterprise 
When i used to bring the data for organization the tokens don't work there but the tokens are working with enterprise URL.

**My Questions**:
1. Do the enterprise metrics will include all the organizations under that access?
2. what is the distinction between enterprise members metrics and organization members?

Thanks in advance. 💯 😊 Appreciate your answer.

**Comment by martedesco** [comment]
> Do the enterprise metrics will include all the organizations under that access?

The enterprise metrics should include metrics of users that have an active Copilot seat in all organizations under it.

> what is the distinction between enterprise members metrics and organization members?

The granularity of the data is the main factor.
