### ISSUE TITLE
team level aggregates

### ISSUE THREAD

**Issue by GeorgeChiran** [github-copilot-resources/copilot-metrics-viewer#71]
Hey folks,

Not clear how is possible to do the team level aggregates. I couldn't find any API that could help link the usage metrics with the teams assigned to repo's. Is there some documentation that you can point me to, on how to do it so I can give it a nudge? or it's something that we are waiting from GITHUB to implement so we can use?

Thanks,
George

**Comment by martedesco** [comment]
We are releasing it this week. Stay tuned to the GitHub blog!
