### ISSUE TITLE
Table Sorting does not seem to work

### ISSUE THREAD

**Issue by dcieslak19973** [github-copilot-resources/copilot-metrics-viewer#74]
Clicking the column headers does not seem to re-sort the data in the associated table

**Comment by Sarah-Pushparaj** [comment]
Opened a pr for this issue: https://github.com/github-copilot-resources/copilot-metrics-viewer/pull/87

**Comment by martedesco** [comment]
Thanks for the contribution @Sarah-Pushparaj ! PR merged 🎉
