### ISSUE TITLE
Show table with user and their last access time

### ISSUE THREAD

**Issue by dcieslak19973** [github-copilot-resources/copilot-metrics-viewer#75]
In order to encourage use of copilot, it would be helpful if there were a sortable table that showed all assigned users and their last (if any) access time in order to solicit users abandoning copilot for feedback.

To be clear - I'm using an "enterprise".  I see that there is logic that appear to restrict the Seat Analysis view to Organizations

**Comment by DevOps-zhuang** [comment]
it seems it is a version regression, We used to update it support enterpise, will double check and update it, thanks for your pointing it out)

**Comment by karpikpl** [comment]
Feature for enterprise seats was merged, does it resolve the issue?

**Comment by dcieslak19973** [comment]
Not sure the policy on this repo for marking issues closed on resolution.  I'll close this issue with this comment
