### ISSUE TITLE
Any plan to adopt --> https://github.blog/changelog/2024-08-09-copilot-metrics-api-organization-team-metrics

### ISSUE THREAD

**Issue by Mayur-Ingale** [github-copilot-resources/copilot-metrics-viewer#77]
Hi @martedesco,

GitHub has finally share that they have released the API for team-level GitHub Copilot metrics (beta).

You can find all the information in our changelog post here - https://github.blog/changelog/2024-08-09-copilot-metrics-api-organization-team-metrics

Any plan to update it in "[copilot-metrics-viewer](https://github.com/github-copilot-resources/copilot-metrics-viewer)" and release the new version 1.7

**Comment by martedesco** [comment]
@Mayur-Ingale , yes, there is an updated planned for this week! 👍🏼

**Comment by martedesco** [comment]
Implemented on [version 1.7](https://github.com/github-copilot-resources/copilot-metrics-viewer/releases/tag/v1.7) 🎉 Closing this Issue for now.
