### ISSUE TITLE
Deployed website is not working

### ISSUE THREAD

**Issue by abagga1c** [github-copilot-resources/copilot-metrics-viewer#78]
Hi,

After deployment on Azure the website is not working, URL: https://ashy-sky-02a7d0403.5.azurestaticapps.net/

Get the following error in console: 
`Error: Invalid VUE_APP_SCOPE value: ${VUE_APP_SCOPE}. Valid values: organization, enterprise`

This used to work around a month ago, but when I pulled latest changes a few days ago it stopped working.

**Comment by martedesco** [comment]
Thanks for flagging, I'm investigating this. I suggest for now keeping the v1.6 release version. 

If you are running from main, the docker run command is slightly different:

```
docker run -p 8080:80 --env-file ./.env copilot-metrics-viewer
```

**Comment by martedesco** [comment]
@abagga1c , the Docker environment variables were externalized in [this PR](https://github.com/github-copilot-resources/copilot-metrics-viewer/pull/48) so you will need to [pass them to your deployment on Azure](https://github.com/github-copilot-resources/copilot-metrics-viewer?tab=readme-ov-file#vue_app_scope). I will update the GitHub Actions deployment workflow and [this is](https://copilot-metrics-viewer-gthcc5cmd9ebf2ff.westeurope-01.azurewebsites.net/) the new link for the deployment! 👍

**Comment by martedesco** [comment]
Fixed and [workflow updated](https://github.com/github-copilot-resources/copilot-metrics-viewer/blob/v1.7/.github/workflows/deploy_to_ghcr.yml). I will close this Issue for now! 🙏🏼

**Comment by martedesco** [comment]
@abagga1c , FYI, it was pushed the [previous image release v1.6](docker pull ghcr.io/github-copilot-resources/copilot-metrics-viewer:1.6) so you can rely on it while you change your setup.

**Comment by abagga1c** [comment]
Thanks a lot for the help and fix @martedesco ! Apologies for the late response. 
While I figure out how to update to the latest changes, will use the v1.6 code .

**Comment by abagga1c** [comment]
Getting stuck on how to deploy the latest code from main.. I built a docker image from main code with values set in .env file and pushed it to container registry. Now I want to run this image as an Azure web app.. but if I understand correctly, I need to tell the app to use .env file somehow?

Any help would be appreciated @martedesco 
Thanks
