### ISSUE TITLE
Cannot display mocked data.

### ISSUE THREAD

**Issue by xuhaoruins** [github-copilot-resources/copilot-metrics-viewer#86]
I am trying to deploy demo site with VUE_APP_MOCKED_DATA=ture in both laptop and Azure environment. But nothing display.

**Comment by martedesco** [comment]
Check if your .env file look like this:

```
# Determines if mocked data should be used instead of making API calls.
VUE_APP_MOCKED_DATA=true

# Determines the scope of the API calls. 
# Can be 'enterprise' or 'organization' to target API calls to an enterprise or an organization respectively.
VUE_APP_SCOPE=organization

# Determines the enterprise or organization name to target API calls.
VUE_APP_GITHUB_ORG=octodemo

VUE_APP_GITHUB_ENT=
```

Run the commands described [here](https://github.com/github-copilot-resources/copilot-metrics-viewer?tab=readme-ov-file#install-dependencies) to run it locally or using a container image.

**Comment by martedesco** [comment]
Glad it worked! Closing this down
