### ISSUE TITLE
Deploying app via docker not passing environmental variables correctly

### ISSUE THREAD

**Issue by DBH1986** [github-copilot-resources/copilot-metrics-viewer#95]
Hello, love the app and I'm wanting to use it on a server. I built and ran the app successfully locally with npm but when I'm trying to run it via docker it starts up okay but hitting localhost throws the below console error

![image](https://github.com/user-attachments/assets/c5a62fd0-f87a-4003-ba96-f80968307a1e)

My environmental variable is set 

![image](https://github.com/user-attachments/assets/b5959e8d-e5aa-4d4b-9e05-b66e75382285)

So it looks like since its working with NPM, the environmental variable isn't being passed along correctly in docker. Looking online this might be due to the EOF characters being different between windows and linux, but changing between the two then redeploying gives the same error.

Ultimately, I'd like to get this image deployed to Azure App Services by following https://learn.microsoft.com/en-us/azure/app-service/quickstart-custom-container?tabs=dotnet&pivots=container-linux-vscode. I've tried this a few times (thinking the docker container error may be a local error), but am getting the same error. This may just be a lack of docker knowledge on my part, but any suggestions for how to get this app running via docker locally and via Azure?

Thanks!

**Comment by DBH1986** [comment]
Hey Piotr, hadn't configured them on the app service itself. I just tried that

![image](https://github.com/user-attachments/assets/d694de5a-25b9-471a-b79d-620e06219d00)
and got the same error after restarting the app service
![image](https://github.com/user-attachments/assets/01526be0-1911-42ff-8d83-b2ea6700792d)

I'll check out the deploy to azure branch too. I'm also wondering why its not working via docker locally on my dev machine so wondering if you have any thoughts on that.

Thanks for the quick response!

**Comment by karpikpl** [comment]
Hey,
I've just tested with a web app:

1. Deployment center -> registry settings:
   1. Registry Source: `Private Registry`
   2. Server URL: `https://ghcr.io`
   3. Full Image Name and Tag: `github-copilot-resources/copilot-metrics-viewer:latest`
1. Environment variables: App settings:
   1. `VUE_APP_GITHUB_ORG` : `your-org-name`
   2. `VUE_APP_SCOPE` : `organization`
   3. `VUE_APP_GITHUB_TOKEN`: `github_pat_xxx` - token with copilot billing read access in the `your-org-name`

keep in mind that your toke will be exposed in the browser unless you look at that PR that I've provided which has means to hide it.

**Comment by DBH1986** [comment]
The image I have is on an Azure container registry, so I'm using that vs pointing out to a website

![image](https://github.com/user-attachments/assets/253896d7-62de-410c-a68d-52894c7700c8)

and I have my env variables set

![image](https://github.com/user-attachments/assets/e33ce786-20b0-4dba-a094-ea3a24440dfe)

but I'm still getting the same error. If I look at the deployment center logs, it looks like its pulling the image okay

`Container copilot-1_1_0886f8b1 for site copilot-1 initialized successfully and is ready to serve requests.`

but it doesn't appear the environment variables are passed along to the docker run

`docker run -d --expose=80 --name copilot-1_1_0886f8b1 -e WEBSITE_USE_DIAGNOSTIC_SERVER=false -e WEBSITE_SITE_NAME=[redacted] -e WEBSITE_AUTH_ENABLED=False -e PORT=80 -e WEBSITE_ROLE_INSTANCE_ID=0 -e WEBSITE_HOSTNAME=[redacted] -e WEBSITE_INSTANCE_ID=d57777f658ca9f9f2da924e41cbfa825a4b4424906804138cc182917f70d653b containerregistry.azurecr.io/copilot-metrics-viewer:v4`

So maybe that's what going on?

**Comment by DBH1986** [comment]
Ah, I think something either was messed up with my docker image or from the main branch. I just built and went through the deploy process using the `feature/configuration` branch and after I set the environment variables up in Azure it started working. I'm going to just continue to use that branch until it has been merged into main. Thank you for your help Piotr!

**Comment by karpikpl** [comment]
my guess that maybe the image you had was stale?
there was a feature me merged recently to handle env variables in docker.

I'll close this issue
