### ISSUE TITLE
Assigning Team is empty

### ISSUE THREAD

**Issue by oguzgu** [github-copilot-resources/copilot-metrics-viewer#96]
Hello,

In the "Seat Analysis" section the "Assigning Team" column is currently displaying as empty for all entries. This information is crucial for analyzing how teams are utilizing Copilot, and its absence is limiting our ability to gain insights on a team-based level.

Steps to Reproduce:

Navigate to the Copilot usage metrics project.
Go to the "Seat Analysis" section.
Check the "Assigning Team" column.
Expected Behavior: The "Assigning Team" column should display the relevant team information associated with each entry.

Actual Behavior: The "Assigning Team" column is empty for all entries.

![Ekran Resmi 2024-09-26 13 28 20](https://github.com/user-attachments/assets/a7a866ca-2200-4797-9bc7-4e6497ba2f48)

**Comment by karpikpl** [comment]
hey @oguzgu 
can you check the API response?
Are you using organization or enterprise API?

The API returns `assigning_team` in the response when copilot license was assigned via team assignment:
https://docs.github.com/en/enterprise-cloud@latest/rest/copilot/copilot-user-management?apiVersion=2022-11-28#list-all-copilot-seat-assignments-for-an-enterprise

**Comment by oguzgu** [comment]
hey @karpikpl 
We are using organization API.
We checked the API response, but it does not contain `assigning_team` in the response.

**Comment by karpikpl** [comment]
can you check your copilot assignments? maybe users were granted copilot access directly?

that's how it looks in my test org:
![image](https://github.com/user-attachments/assets/9c6902c1-e91e-4413-b071-b82cf8a234f2)

**Comment by oguzgu** [comment]
yes, users were granted copilot access directly? Is it possible now to change it?

**Comment by karpikpl** [comment]
I'm not a GitHub employee so please take that into consideration.

If you want to see that field populated, you can:
1. create Teams (possibly teams that are synced with Entra),
2. add users to those teams.
3. assign copilot license to that team
4. remove direct assignment

I'd just test on one user before applying globally.

I think copilot-metrics solution is working correctly, so I'll close this issue.
